### ISSUE TITLE
Exception lors de la deconnexion client

### ISSUE THREAD

**Issue by CrazyMeal** [CrazyMeal/ProcessServerLauncher#2]
Lorsque le server tourne, qu'un client s'y est connecté puis que le client est coupé, une exception survient:
java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:209)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at java.net.SocketInputStream.read(SocketInputStream.java:127)
    at net.NetDataReader.readByte(NetDataReader.java:52)
    at net.NetDataReader.readDiscriminant(NetDataReader.java:18)
    at net.RemoteClientService.run(RemoteClientService.java:28)
    at java.lang.Thread.run(Thread.java:745)

Process finished with exit code -1

**Comment by CrazyMeal** [comment]
Le principe de communication entre Client-Server change. Dorénavant on ne maintient pas une connection ouverte en permanence entre les deux.

Chaque action client implique donc qu'il doit d'abord se connecter au server, puis procéder à d'autre actions
